language: python
python:
  - "3.10.6"
install:
  - pip install -r requirements.txt
  - pip install coverage
  - pip install coveralls
script:
  - python -m unittest discover -s tests
  - coverage run --omit=*.virtualenvs*,*virtualenv* -m unittest discover tests
after_success:
  - coveralls